export const SET_BILLS = "SET_BILLS";
export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";
export const ADD_BILL = "ADD_BILL";
export const EDIT_BILL = "EDIT_BILL";
export const DELETE_BILL = "DELETE_BILL";
export const SET_HIGHLIGHTED_INDEXES = "SET_HIGHLIGHTED_INDEXES"
export const REMOVE_HIGHLIGHTED_INDEX = "REMOVE_HIGHLIGHTED_INDEX"